version: "3"

services:

  mysql:
    image: "mysql:5.7.20"
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=hayat

  spring-boot-app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST_NAME=mysql
      - MYSQL_HOST_NAME=33060

