
spring:
  application:
    name: project-app

server:
  port: ${PORT:0}
  servlet:
#    context-path: /PROJET-API
    multipart.max-file-size: 30MB


logging:
  level:
    org.springframework:
      web: DEBUG
      security: DEBUG


#spring.mvc.static-path-pattern=/REACT-APP/**
#spring.resources.static-locations=classpath:/REACT-APP/
#spring.mvc.view.prefix=classpath:/REACT-APP/

gateway.ip: '192.168.1.5'

spring.jpa.open-in-view: false
